"""
Data models for Racing Analytics API.
"""

from .models import (
    FactorScore,
    TrackDemand,
    Track,
    DriverStats,
    Driver,
    CircuitFitPrediction,
    ChatMessage,
    ChatRequest,
    ChatResponse,
    LapData,
    TelemetryComparison,
    SeasonStats,
    RaceResult,
    FactorVariable,
    FactorBreakdownResponse,
    DriverFactorComparison,
    FactorComparisonResponse,
    AdjustedSkills,
    PredictionWithUncertainty,
    FindSimilarDriverRequest,
    SimilarDriverMatch,
    ImprovementRecommendation,
    ImprovePredictionResponse,
    TelemetryPoint,
    CornerAnalysis,
    TelemetryCoachingRequest,
    TelemetryCoachingResponse,
    PracticePlanRequest,
    PracticePlanResponse,
    WeeklyMilestone,
    SkillPriority,
    FinalPrediction,
    # Skills Page - Coach View Models
    SkillGapItem,
    SkillGapAnalysisResponse,
    CoachRecommendation,
    CoachRecommendationsResponse,
    # Development Page - Projection Models
    ProjectedDriverRanking,
    ProjectedRankingsResponse,
    TrackImprovementFocus,
    TrackImprovementPlanResponse,
)

__all__ = [
    "FactorScore",
    "TrackDemand",
    "Track",
    "DriverStats",
    "Driver",
    "CircuitFitPrediction",
    "ChatMessage",
    "ChatRequest",
    "ChatResponse",
    "LapData",
    "TelemetryComparison",
    "SeasonStats",
    "RaceResult",
    "FactorVariable",
    "FactorBreakdownResponse",
    "DriverFactorComparison",
    "FactorComparisonResponse",
    "AdjustedSkills",
    "PredictionWithUncertainty",
    "FindSimilarDriverRequest",
    "SimilarDriverMatch",
    "ImprovementRecommendation",
    "ImprovePredictionResponse",
    "TelemetryPoint",
    "CornerAnalysis",
    "TelemetryCoachingRequest",
    "TelemetryCoachingResponse",
    "PracticePlanRequest",
    "PracticePlanResponse",
    "WeeklyMilestone",
    "SkillPriority",
    "FinalPrediction",
    # Skills Page - Coach View Models
    "SkillGapItem",
    "SkillGapAnalysisResponse",
    "CoachRecommendation",
    "CoachRecommendationsResponse",
    # Development Page - Projection Models
    "ProjectedDriverRanking",
    "ProjectedRankingsResponse",
    "TrackImprovementFocus",
    "TrackImprovementPlanResponse",
]
